[package]
name = "rlox"
version = "0.1.0"
authors = ["Christian Briones <cwbriones@gmail.com>"]

[dependencies]
rustyline = "*"
env_logger = "*"
log = "*"
failure = "0.1.1"
parser = { path = "../parser" }
